### ISSUE TITLE
118 kB bundle size?

### ISSUE THREAD

**Issue by skirsten** [nikolovlazar/chakra-ui-prose#7]
After adding the `withProse` to the `extendTheme` my Next.js bundle size shot up a lot, about 118 kB.

```
before:
chunks/pages/_app-57c7e4e7ff00db3f.js  52.3 kB
after:
chunks/pages/_app-af31a7e4f630c391.js  170 kB
```

Considering that the source in this repo is ~ 4 kB I don't know what is happening here. Is this expected or is something wrong?

If this is expected, is it possible to only include the `withProse` in specific routes (nested `ChakraProvider`)?

**Comment by nikolovlazar** [comment]
Turns out I've been packing the `tsconfig.tsbuildinfo`, which added 92 kB. I'll push a new patch that fixes this. Thanks for raising this issue @skirsten!

**Comment by nikolovlazar** [comment]
@skirsten I've published version `1.0.7`. The unpacked size is now at 17kB as opposed to 109kB previously.

**Comment by skirsten** [comment]
Thanks, unfortunately this did not fix the issue. I think there is something wrong with the imports or the JSX.
The `@chakra-ui/system` import should be `@chakra-ui/react` and maybe the `react` import has to be removed.

For now, I just copy pasted the source directly into my Next.js project and fixed the imports. This increased the `_app` bundle by only 0.9 kB :tada: .
